services:
  web:
    image: 56025192/mcsm-web:latest
    ports:
      - "80:23333"
    volumes:
      - ./data/web/data:/opt/mcsmanager/web/data
      - ./data/web/logs:/opt/mcsmanager/web/logs

  daemon:
    image: 56025192/mcsm-daemon:latest
    ports:
      - "24444:24444"
    volumes:
      - ./data/daemon/data:/opt/mcsmanager/daemon/data
      - ./data/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
