version: '3'

services:
  web:
    image: mcsm/web
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - "80:23333"
    volumes:
      - ./web/data:/ops/mcsmanager/web/data
      - ./web/logs:/ops/mcsmanager/web/logs

  daemon:
    image: mcsm/daemon
    build:
      context: .
      dockerfile: daemon.dockerfile
    ports:
      - "24444:24444"
    volumes:
      - ./daemon/data:/ops/mcsmanager/daemon/data
      - ./daemon/logs:/ops/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
