version: '3'

services:
  web:
    image: kagurazakanyaa/mcsm:web
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:23333"
    volumes:
      - ./data/web/data:/ops/mcsmanager/web/data
      - ./data/web/logs:/ops/mcsmanager/web/logs

  daemon:
    image: kagurazakanyaa/mcsm:daemon
    build:
      context: daemon
      dockerfile: Dockerfile
    ports:
      - "24444:24444"
    volumes:
      - ./data/daemon/data:/ops/mcsmanager/daemon/data
      - ./data/daemon/logs:/ops/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
