name: Build Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta web
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: kagurazakanyaa/mcsm-web

      - name: Docker meta daemon
        id: meta_daemon
        uses: docker/metadata-action@v5
        with:
          images: kagurazakanyaa/mcsm-daemon

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: web.dockerfile
          push: true
          build-args: |
            VERSION_TAG=${{ github.ref_name }}
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: daemon.dockerfile
          push: true
          build-args: |
            VERSION_TAG=${{ github.ref_name }}
          tags: ${{ steps.meta_daemon.outputs.tags }}
          labels: ${{ steps.meta_daemon.outputs.labels }}
