name: Check upstream update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run update script
        run: ./checkupdate.sh
        shell: bash
