name: Build Web Docker Image

on:
  push:
    paths:
      - "web/version"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: web
          dockerfile: Dockerfile
          tags: kagurazakanyaa/mcsm:web
